/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Image = IDL.Vec(IDL.Nat8);
export const CreatePostResult = IDL.Variant({
  'ok' : IDL.Nat,
  'imageTooLarge' : IDL.Null,
});
export const DeleteCommentResult = IDL.Variant({
  'ok' : IDL.Null,
  'notFound' : IDL.Null,
  'notOwner' : IDL.Null,
});
export const EditCommentResult = IDL.Variant({
  'ok' : IDL.Null,
  'notFound' : IDL.Null,
  'notOwner' : IDL.Null,
});
export const PostStatus = IDL.Variant({
  'published' : IDL.Null,
  'hidden' : IDL.Null,
  'draft' : IDL.Null,
});
export const Time = IDL.Int;
export const Post = IDL.Record({
  'id' : IDL.Nat,
  'status' : PostStatus,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'ownerId' : IDL.Principal,
  'createdAt' : Time,
  'likedBy' : IDL.Vec(IDL.Principal),
  'author' : IDL.Text,
  'dislikedBy' : IDL.Vec(IDL.Principal),
  'images' : IDL.Vec(Image),
});
export const UserProfile = IDL.Record({
  'preferredLanguage' : IDL.Text,
  'country' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const AuthorInfo = IDL.Record({
  'principal' : IDL.Principal,
  'displayName' : IDL.Text,
});
export const Comment = IDL.Record({
  'id' : IDL.Nat,
  'isDeleted' : IDL.Bool,
  'content' : IDL.Text,
  'createdAt' : Time,
  'authorAlias' : IDL.Text,
  'authorPrincipal' : IDL.Principal,
  'postId' : IDL.Nat,
  'images' : IDL.Vec(IDL.Vec(IDL.Nat8)),
});
export const GetCommentsResult = IDL.Variant({
  'ok' : IDL.Vec(Comment),
  'postNotFound' : IDL.Null,
});
export const Notification = IDL.Record({
  'id' : IDL.Nat,
  'createdAt' : Time,
  'isRead' : IDL.Bool,
  'commenterAlias' : IDL.Text,
  'postTitle' : IDL.Text,
  'recipientPrincipal' : IDL.Principal,
  'postId' : IDL.Nat,
});
export const ReactionCount = IDL.Record({
  'likes' : IDL.Nat,
  'dislikes' : IDL.Nat,
});
export const PublicProfile = IDL.Record({
  'principal' : IDL.Principal,
  'alias' : IDL.Text,
});
export const UpdatePostResult = IDL.Variant({
  'ok' : IDL.Null,
  'postNotFound' : IDL.Null,
  'imageTooLarge' : IDL.Null,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAdmin' : IDL.Func([IDL.Principal], [], []),
  'addComment' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearAllNotifications' : IDL.Func([], [], []),
  'createPost' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(Image)],
      [CreatePostResult],
      [],
    ),
  'deleteComment' : IDL.Func([IDL.Nat], [DeleteCommentResult], []),
  'deleteDraft' : IDL.Func([IDL.Nat], [], []),
  'deletePost' : IDL.Func([IDL.Nat], [], []),
  'dislikePost' : IDL.Func([IDL.Nat], [], []),
  'editComment' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Vec(IDL.Vec(IDL.Nat8))],
      [EditCommentResult],
      [],
    ),
  'followUser' : IDL.Func([IDL.Principal], [], []),
  'getAdmins' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getAllPostsAdmin' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'getAllProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getAllPublishedPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'getAuthors' : IDL.Func([], [IDL.Vec(AuthorInfo)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCommentsForPost' : IDL.Func([IDL.Nat], [GetCommentsResult], ['query']),
  'getDraft' : IDL.Func([IDL.Nat], [Post], ['query']),
  'getFollowedUsers' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getFollowerCount' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
  'getMyDrafts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getPost' : IDL.Func([IDL.Nat], [Post], ['query']),
  'getPostReactions' : IDL.Func([IDL.Nat], [ReactionCount], ['query']),
  'getPreferredLanguage' : IDL.Func([], [IDL.Text], ['query']),
  'getPublicProfiles' : IDL.Func([], [IDL.Vec(PublicProfile)], ['query']),
  'getUnreadNotificationCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isAdmin' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isFollowing' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'likePost' : IDL.Func([IDL.Nat], [], []),
  'markNotificationRead' : IDL.Func([IDL.Nat], [], []),
  'promoteUser' : IDL.Func([IDL.Principal], [], []),
  'publishDraft' : IDL.Func([IDL.Nat], [UpdatePostResult], []),
  'removeAdmin' : IDL.Func([IDL.Principal], [], []),
  'removeAuthor' : IDL.Func([IDL.Principal], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveDraft' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(Image)],
      [IDL.Nat],
      [],
    ),
  'setOwner' : IDL.Func([IDL.Principal], [], []),
  'setPreferredLanguage' : IDL.Func([IDL.Text], [], []),
  'unfollowUser' : IDL.Func([IDL.Principal], [], []),
  'updateDraft' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(Image)],
      [],
      [],
    ),
  'updatePost' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, PostStatus, IDL.Vec(Image)],
      [UpdatePostResult],
      [],
    ),
  'updateUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Image = IDL.Vec(IDL.Nat8);
  const CreatePostResult = IDL.Variant({
    'ok' : IDL.Nat,
    'imageTooLarge' : IDL.Null,
  });
  const DeleteCommentResult = IDL.Variant({
    'ok' : IDL.Null,
    'notFound' : IDL.Null,
    'notOwner' : IDL.Null,
  });
  const EditCommentResult = IDL.Variant({
    'ok' : IDL.Null,
    'notFound' : IDL.Null,
    'notOwner' : IDL.Null,
  });
  const PostStatus = IDL.Variant({
    'published' : IDL.Null,
    'hidden' : IDL.Null,
    'draft' : IDL.Null,
  });
  const Time = IDL.Int;
  const Post = IDL.Record({
    'id' : IDL.Nat,
    'status' : PostStatus,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'ownerId' : IDL.Principal,
    'createdAt' : Time,
    'likedBy' : IDL.Vec(IDL.Principal),
    'author' : IDL.Text,
    'dislikedBy' : IDL.Vec(IDL.Principal),
    'images' : IDL.Vec(Image),
  });
  const UserProfile = IDL.Record({
    'preferredLanguage' : IDL.Text,
    'country' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const AuthorInfo = IDL.Record({
    'principal' : IDL.Principal,
    'displayName' : IDL.Text,
  });
  const Comment = IDL.Record({
    'id' : IDL.Nat,
    'isDeleted' : IDL.Bool,
    'content' : IDL.Text,
    'createdAt' : Time,
    'authorAlias' : IDL.Text,
    'authorPrincipal' : IDL.Principal,
    'postId' : IDL.Nat,
    'images' : IDL.Vec(IDL.Vec(IDL.Nat8)),
  });
  const GetCommentsResult = IDL.Variant({
    'ok' : IDL.Vec(Comment),
    'postNotFound' : IDL.Null,
  });
  const Notification = IDL.Record({
    'id' : IDL.Nat,
    'createdAt' : Time,
    'isRead' : IDL.Bool,
    'commenterAlias' : IDL.Text,
    'postTitle' : IDL.Text,
    'recipientPrincipal' : IDL.Principal,
    'postId' : IDL.Nat,
  });
  const ReactionCount = IDL.Record({ 'likes' : IDL.Nat, 'dislikes' : IDL.Nat });
  const PublicProfile = IDL.Record({
    'principal' : IDL.Principal,
    'alias' : IDL.Text,
  });
  const UpdatePostResult = IDL.Variant({
    'ok' : IDL.Null,
    'postNotFound' : IDL.Null,
    'imageTooLarge' : IDL.Null,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAdmin' : IDL.Func([IDL.Principal], [], []),
    'addComment' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearAllNotifications' : IDL.Func([], [], []),
    'createPost' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(Image)],
        [CreatePostResult],
        [],
      ),
    'deleteComment' : IDL.Func([IDL.Nat], [DeleteCommentResult], []),
    'deleteDraft' : IDL.Func([IDL.Nat], [], []),
    'deletePost' : IDL.Func([IDL.Nat], [], []),
    'dislikePost' : IDL.Func([IDL.Nat], [], []),
    'editComment' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Vec(IDL.Vec(IDL.Nat8))],
        [EditCommentResult],
        [],
      ),
    'followUser' : IDL.Func([IDL.Principal], [], []),
    'getAdmins' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'getAllPostsAdmin' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'getAllProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getAllPublishedPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'getAuthors' : IDL.Func([], [IDL.Vec(AuthorInfo)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCommentsForPost' : IDL.Func([IDL.Nat], [GetCommentsResult], ['query']),
    'getDraft' : IDL.Func([IDL.Nat], [Post], ['query']),
    'getFollowedUsers' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'getFollowerCount' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
    'getMyDrafts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getPost' : IDL.Func([IDL.Nat], [Post], ['query']),
    'getPostReactions' : IDL.Func([IDL.Nat], [ReactionCount], ['query']),
    'getPreferredLanguage' : IDL.Func([], [IDL.Text], ['query']),
    'getPublicProfiles' : IDL.Func([], [IDL.Vec(PublicProfile)], ['query']),
    'getUnreadNotificationCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isAdmin' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isFollowing' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'likePost' : IDL.Func([IDL.Nat], [], []),
    'markNotificationRead' : IDL.Func([IDL.Nat], [], []),
    'promoteUser' : IDL.Func([IDL.Principal], [], []),
    'publishDraft' : IDL.Func([IDL.Nat], [UpdatePostResult], []),
    'removeAdmin' : IDL.Func([IDL.Principal], [], []),
    'removeAuthor' : IDL.Func([IDL.Principal], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveDraft' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(Image)],
        [IDL.Nat],
        [],
      ),
    'setOwner' : IDL.Func([IDL.Principal], [], []),
    'setPreferredLanguage' : IDL.Func([IDL.Text], [], []),
    'unfollowUser' : IDL.Func([IDL.Principal], [], []),
    'updateDraft' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(Image)],
        [],
        [],
      ),
    'updatePost' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, PostStatus, IDL.Vec(Image)],
        [UpdatePostResult],
        [],
      ),
    'updateUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };