/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AuthorInfo { 'principal' : Principal, 'displayName' : string }
export interface Comment {
  'id' : bigint,
  'isDeleted' : boolean,
  'content' : string,
  'createdAt' : Time,
  'authorAlias' : string,
  'authorPrincipal' : Principal,
  'postId' : bigint,
  'images' : Array<Uint8Array>,
}
export type CreatePostResult = { 'ok' : bigint } |
  { 'imageTooLarge' : null };
export type DeleteCommentResult = { 'ok' : null } |
  { 'notFound' : null } |
  { 'notOwner' : null };
export type EditCommentResult = { 'ok' : null } |
  { 'notFound' : null } |
  { 'notOwner' : null };
export type GetCommentsResult = { 'ok' : Array<Comment> } |
  { 'postNotFound' : null };
export type Image = Uint8Array;
export interface Notification {
  'id' : bigint,
  'createdAt' : Time,
  'isRead' : boolean,
  'commenterAlias' : string,
  'postTitle' : string,
  'recipientPrincipal' : Principal,
  'postId' : bigint,
}
export interface Post {
  'id' : bigint,
  'status' : PostStatus,
  'title' : string,
  'content' : string,
  'ownerId' : Principal,
  'createdAt' : Time,
  'likedBy' : Array<Principal>,
  'author' : string,
  'dislikedBy' : Array<Principal>,
  'images' : Array<Image>,
}
export type PostStatus = { 'published' : null } |
  { 'hidden' : null } |
  { 'draft' : null };
export interface PublicProfile { 'principal' : Principal, 'alias' : string }
export interface ReactionCount { 'likes' : bigint, 'dislikes' : bigint }
export type Time = bigint;
export type UpdatePostResult = { 'ok' : null } |
  { 'postNotFound' : null } |
  { 'imageTooLarge' : null };
export interface UserProfile {
  'preferredLanguage' : string,
  'country' : string,
  'name' : string,
  'email' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  /**
   * / Add an admin (owner only)
   */
  'addAdmin' : ActorMethod<[Principal], undefined>,
  'addComment' : ActorMethod<
    [bigint, string, string, Array<Uint8Array>],
    bigint
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearAllNotifications' : ActorMethod<[], undefined>,
  /**
   * / Create a post (authenticated users only)
   */
  'createPost' : ActorMethod<
    [string, string, string, Array<Image>],
    CreatePostResult
  >,
  'deleteComment' : ActorMethod<[bigint], DeleteCommentResult>,
  /**
   * / Delete a post (owner of post or admin)
   */
  'deletePost' : ActorMethod<[bigint], undefined>,
  /**
   * / Dislike a post (authenticated users only). Toggles dislike; removes like if present.
   */
  'dislikePost' : ActorMethod<[bigint], undefined>,
  'editComment' : ActorMethod<
    [bigint, string, Array<Uint8Array>],
    EditCommentResult
  >,
  /**
   * / Follow a user (authenticated users only)
   */
  'followUser' : ActorMethod<[Principal], undefined>,
  /**
   * / Get all admins (owner only)
   */
  'getAdmins' : ActorMethod<[], Array<Principal>>,
  /**
   * / Get all posts regardless of status (admins only)
   */
  'getAllPostsAdmin' : ActorMethod<[], Array<Post>>,
  /**
   * / List all profiles (admins only — profiles contain sensitive PII: email, phone, country)
   */
  'getAllProfiles' : ActorMethod<[], Array<UserProfile>>,
  /**
   * / Get all published posts (public)
   */
  'getAllPublishedPosts' : ActorMethod<[], Array<Post>>,
  /**
   * / Get all unique authors and their display names (admins only)
   */
  'getAuthors' : ActorMethod<[], Array<AuthorInfo>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCommentsForPost' : ActorMethod<[bigint], GetCommentsResult>,
  /**
   * / Get list of users the caller follows (authenticated users only)
   */
  'getFollowedUsers' : ActorMethod<[], Array<Principal>>,
  /**
   * / Get follower count for a user (public)
   */
  'getFollowerCount' : ActorMethod<[Principal], bigint>,
  /**
   * / Get all drafts belonging to the caller (authenticated users only)
   */
  'getMyDrafts' : ActorMethod<[], Array<Post>>,
  'getNotifications' : ActorMethod<[], Array<Notification>>,
  /**
   * / Get a single post by ID (public, but only published posts for non-admins)
   */
  'getPost' : ActorMethod<[bigint], Post>,
  /**
   * / Get like/dislike counts for a post (public, no auth required)
   */
  'getPostReactions' : ActorMethod<[bigint], ReactionCount>,
  /**
   * / Get the preferred language for the caller (authenticated users only)
   */
  'getPreferredLanguage' : ActorMethod<[], string>,
  /**
   * / Get all users who have a public profile (name only, must not be empty)
   */
  'getPublicProfiles' : ActorMethod<[], Array<PublicProfile>>,
  'getUnreadNotificationCount' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  /**
   * / Check if a principal is an admin (any authenticated user can check their own status)
   */
  'isAdmin' : ActorMethod<[Principal], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  /**
   * / Check if user is following another user (authenticated users only)
   */
  'isFollowing' : ActorMethod<[Principal], boolean>,
  /**
   * / Like a post (authenticated users only). Toggles like; removes dislike if present.
   */
  'likePost' : ActorMethod<[bigint], undefined>,
  'markNotificationRead' : ActorMethod<[bigint], undefined>,
  /**
   * / Called by admin to promote a principal to user role
   */
  'promoteUser' : ActorMethod<[Principal], undefined>,
  /**
   * / Remove an admin (owner only). The owner cannot be removed.
   */
  'removeAdmin' : ActorMethod<[Principal], undefined>,
  /**
   * / Remove all posts belonging to an author (admins only)
   */
  'removeAuthor' : ActorMethod<[Principal], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  /**
   * / Save a new draft (authenticated users only)
   */
  'saveDraft' : ActorMethod<[string, string, string, Array<Image>], bigint>,
  /**
   * / Set a new owner (owner only)
   */
  'setOwner' : ActorMethod<[Principal], undefined>,
  /**
   * / Set the preferred language for the caller (authenticated users only)
   */
  'setPreferredLanguage' : ActorMethod<[string], undefined>,
  /**
   * / Unfollow a user (authenticated users only)
   */
  'unfollowUser' : ActorMethod<[Principal], undefined>,
  /**
   * / Update an existing draft (authenticated users only, owner of draft only)
   */
  'updateDraft' : ActorMethod<
    [bigint, string, string, string, Array<Image>],
    undefined
  >,
  /**
   * / Update a post (owner of post or admin)
   */
  'updatePost' : ActorMethod<
    [bigint, string, string, string, PostStatus, Array<Image>],
    UpdatePostResult
  >,
  'updateUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];