/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AuthorInfo { 'principal' : Principal, 'displayName' : string }
export type Image = Uint8Array;
export interface Post {
  'id' : bigint,
  'status' : PostStatus,
  'title' : string,
  'content' : string,
  'ownerId' : Principal,
  'createdAt' : Time,
  'author' : string,
  'images' : Array<Image>,
}
export type PostStatus = { 'published' : null } |
  { 'hidden' : null } |
  { 'draft' : null };
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  /**
   * / Add an admin (owner only)
   */
  'addAdmin' : ActorMethod<[Principal], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  /**
   * / Create a post (authenticated users only)
   */
  'createPost' : ActorMethod<[string, string, string, Array<Image>], bigint>,
  /**
   * / Delete a post (owner of post or admin)
   */
  'deletePost' : ActorMethod<[bigint], undefined>,
  /**
   * / Get all admins (owner only)
   */
  'getAdmins' : ActorMethod<[], Array<Principal>>,
  /**
   * / Get all posts regardless of status (admins only)
   */
  'getAllPostsAdmin' : ActorMethod<[], Array<Post>>,
  /**
   * / Get all published posts (public)
   */
  'getAllPublishedPosts' : ActorMethod<[], Array<Post>>,
  /**
   * / Get all unique authors and their display names (admins only)
   */
  'getAuthors' : ActorMethod<[], Array<AuthorInfo>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  /**
   * / Get a single post by ID (public, but only published posts for non-admins)
   */
  'getPost' : ActorMethod<[bigint], Post>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  /**
   * / Check if a principal is an admin (any authenticated user can check their own status)
   */
  'isAdmin' : ActorMethod<[Principal], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  /**
   * / Remove an admin (owner only). The owner cannot be removed.
   */
  'removeAdmin' : ActorMethod<[Principal], undefined>,
  /**
   * / Remove all posts belonging to an author (admins only)
   */
  'removeAuthor' : ActorMethod<[Principal], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  /**
   * / Set a new owner (owner only)
   */
  'setOwner' : ActorMethod<[Principal], undefined>,
  /**
   * / Update a post (owner of post or admin)
   */
  'updatePost' : ActorMethod<
    [bigint, string, string, string, PostStatus, Array<Image>],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];