/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ReactionCount {
    likes: bigint;
    dislikes: bigint;
}
export type Time = bigint;
export type CreatePostResult = {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "imageTooLarge";
    imageTooLarge: null;
};
export type GetCommentsResult = {
    __kind__: "ok";
    ok: Array<Comment>;
} | {
    __kind__: "postNotFound";
    postNotFound: null;
};
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Comment {
    id: bigint;
    isDeleted: boolean;
    content: string;
    createdAt: Time;
    authorAlias: string;
    authorPrincipal: Principal;
    postId: bigint;
    images: Array<Uint8Array>;
}
export interface AuthorInfo {
    principal: Principal;
    displayName: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface PublicProfile {
    principal: Principal;
    alias: string;
}
export interface Post {
    id: bigint;
    status: PostStatus;
    title: string;
    content: string;
    ownerId: Principal;
    createdAt: Time;
    likedBy: Array<Principal>;
    author: string;
    dislikedBy: Array<Principal>;
    images: Array<Image>;
}
export interface Notification {
    id: bigint;
    createdAt: Time;
    isRead: boolean;
    commenterAlias: string;
    postTitle: string;
    recipientPrincipal: Principal;
    postId: bigint;
}
export type Image = Uint8Array;
export interface UserProfile {
    preferredLanguage: string;
    country: string;
    name: string;
    email: string;
    phone: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum DeleteCommentResult {
    ok = "ok",
    notFound = "notFound",
    notOwner = "notOwner"
}
export enum PostStatus {
    published = "published",
    hidden = "hidden",
    draft = "draft"
}
export enum UpdatePostResult {
    ok = "ok",
    postNotFound = "postNotFound",
    imageTooLarge = "imageTooLarge"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    /**
     * / Add an admin (owner only)
     */
    addAdmin(principal: Principal): Promise<void>;
    addComment(postId: bigint, content: string, authorAlias: string, images: Array<Uint8Array>): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    clearAllNotifications(): Promise<void>;
    /**
     * / Create a post (authenticated users only)
     */
    createPost(title: string, content: string, author: string, images: Array<Image>): Promise<CreatePostResult>;
    deleteComment(commentId: bigint): Promise<DeleteCommentResult>;
    /**
     * / Delete a draft by ID (authenticated users only, owner of draft only)
     */
    deleteDraft(id: bigint): Promise<void>;
    /**
     * / Delete a post (owner of post or admin)
     */
    deletePost(id: bigint): Promise<void>;
    /**
     * / Dislike a post (authenticated users only). Toggles dislike; removes like if present.
     */
    dislikePost(postId: bigint): Promise<void>;
    editComment(commentId: bigint, content: string, images: Array<Uint8Array>): Promise<EditCommentResult>;
    /**
     * / Follow a user (authenticated users only)
     */
    followUser(target: Principal): Promise<void>;
    /**
     * / Get all admins (owner only)
     */
    getAdmins(): Promise<Array<Principal>>;
    /**
     * / Get all posts regardless of status (admins only)
     */
    getAllPostsAdmin(): Promise<Array<Post>>;
    /**
     * / List all profiles (admins only — profiles contain sensitive PII: email, phone, country)
     */
    getAllProfiles(): Promise<Array<UserProfile>>;
    /**
     * / Get all published posts (public)
     */
    getAllPublishedPosts(): Promise<Array<Post>>;
    /**
     * / Get all unique authors and their display names (admins only)
     */
    getAuthors(): Promise<Array<AuthorInfo>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCommentsForPost(postId: bigint): Promise<GetCommentsResult>;
    /**
     * / Get a specific draft by ID (authenticated users only, owner of draft only)
     */
    getDraft(id: bigint): Promise<Post>;
    /**
     * / Get list of users the caller follows (authenticated users only)
     */
    getFollowedUsers(): Promise<Array<Principal>>;
    /**
     * / Get follower count for a user (public)
     */
    getFollowerCount(target: Principal): Promise<bigint>;
    /**
     * / Get all drafts belonging to the caller (authenticated users only)
     */
    getMyDrafts(): Promise<Array<Post>>;
    getNotifications(): Promise<Array<Notification>>;
    /**
     * / Get a single post by ID (public, but only published posts for non-admins)
     */
    getPost(id: bigint): Promise<Post>;
    /**
     * / Get like/dislike counts for a post (public, no auth required)
     */
    getPostReactions(postId: bigint): Promise<ReactionCount>;
    /**
     * / Get the preferred language for the caller (authenticated users only)
     */
    getPreferredLanguage(): Promise<string>;
    /**
     * / Get all users who have a public profile (name only, must not be empty)
     */
    getPublicProfiles(): Promise<Array<PublicProfile>>;
    getUnreadNotificationCount(): Promise<bigint>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    /**
     * / Check if a principal is an admin (any authenticated user can check their own status)
     */
    isAdmin(principal: Principal): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    /**
     * / Check if user is following another user (authenticated users only)
     */
    isFollowing(target: Principal): Promise<boolean>;
    /**
     * / Like a post (authenticated users only). Toggles like; removes dislike if present.
     */
    likePost(postId: bigint): Promise<void>;
    markNotificationRead(notificationId: bigint): Promise<void>;
    /**
     * / Called by admin to promote a principal to user role
     */
    promoteUser(user: Principal): Promise<void>;
    /**
     * / Publish a draft (authenticated users only, owner of draft only)
     */
    publishDraft(id: bigint): Promise<UpdatePostResult>;
    /**
     * / Remove an admin (owner only). The owner cannot be removed.
     */
    removeAdmin(principal: Principal): Promise<void>;
    /**
     * / Remove all posts belonging to an author (admins only)
     */
    removeAuthor(principal: Principal): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    /**
     * / Save a new draft (authenticated users only)
     */
    saveDraft(title: string, content: string, author: string, images: Array<Image>): Promise<bigint>;
    /**
     * / Set a new owner (owner only)
     */
    setOwner(newOwner: Principal): Promise<void>;
    /**
     * / Set the preferred language for the caller (authenticated users only)
     */
    setPreferredLanguage(language: string): Promise<void>;
    /**
     * / Unfollow a user (authenticated users only)
     */
    unfollowUser(target: Principal): Promise<void>;
    /**
     * / Update an existing draft (authenticated users only, owner of draft only)
     */
    updateDraft(id: bigint, title: string, content: string, author: string, images: Array<Image>): Promise<void>;
    /**
     * / Update a post (owner of post or admin)
     */
    updatePost(id: bigint, title: string, content: string, author: string, status: PostStatus, images: Array<Image>): Promise<UpdatePostResult>;
    updateUserProfile(profile: UserProfile): Promise<void>;
}
import type { Comment as _Comment, CreatePostResult as _CreatePostResult, DeleteCommentResult as _DeleteCommentResult, EditCommentResult as _EditCommentResult, GetCommentsResult as _GetCommentsResult, Image as _Image, Post as _Post, PostStatus as _PostStatus, Time as _Time, UpdatePostResult as _UpdatePostResult, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addAdmin(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addAdmin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAdmin(arg0);
            return result;
        }
    }
    async addComment(arg0: bigint, arg1: string, arg2: string, arg3: Array<Uint8Array>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addComment(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addComment(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async clearAllNotifications(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearAllNotifications();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearAllNotifications();
            return result;
        }
    }
    async createPost(arg0: string, arg1: string, arg2: string, arg3: Array<Image>): Promise<CreatePostResult> {
        if (this.processError) {
            try {
                const result = await this.actor.createPost(arg0, arg1, arg2, arg3);
                return from_candid_CreatePostResult_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPost(arg0, arg1, arg2, arg3);
            return from_candid_CreatePostResult_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteComment(arg0: bigint): Promise<DeleteCommentResult> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteComment(arg0);
                return from_candid_DeleteCommentResult_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteComment(arg0);
            return from_candid_DeleteCommentResult_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteDraft(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDraft(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDraft(arg0);
            return result;
        }
    }
    async deletePost(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePost(arg0);
            return result;
        }
    }
    async dislikePost(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.dislikePost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.dislikePost(arg0);
            return result;
        }
    }
    async editComment(arg0: bigint, arg1: string, arg2: Array<Uint8Array>): Promise<EditCommentResult> {
        if (this.processError) {
            try {
                const result = await this.actor.editComment(arg0, arg1, arg2);
                return from_candid_EditCommentResult_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editComment(arg0, arg1, arg2);
            return from_candid_EditCommentResult_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async followUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.followUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.followUser(arg0);
            return result;
        }
    }
    async getAdmins(): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdmins();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdmins();
            return result;
        }
    }
    async getAllPostsAdmin(): Promise<Array<Post>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPostsAdmin();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPostsAdmin();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllProfiles(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProfiles();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProfiles();
            return result;
        }
    }
    async getAllPublishedPosts(): Promise<Array<Post>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPublishedPosts();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPublishedPosts();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAuthors(): Promise<Array<AuthorInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAuthors();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAuthors();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCommentsForPost(arg0: bigint): Promise<GetCommentsResult> {
        if (this.processError) {
            try {
                const result = await this.actor.getCommentsForPost(arg0);
                return from_candid_GetCommentsResult_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCommentsForPost(arg0);
            return from_candid_GetCommentsResult_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDraft(arg0: bigint): Promise<Post> {
        if (this.processError) {
            try {
                const result = await this.actor.getDraft(arg0);
                return from_candid_Post_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDraft(arg0);
            return from_candid_Post_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFollowedUsers(): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFollowedUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFollowedUsers();
            return result;
        }
    }
    async getFollowerCount(arg0: Principal): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getFollowerCount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFollowerCount(arg0);
            return result;
        }
    }
    async getMyDrafts(): Promise<Array<Post>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyDrafts();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyDrafts();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNotifications(): Promise<Array<Notification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotifications();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotifications();
            return result;
        }
    }
    async getPost(arg0: bigint): Promise<Post> {
        if (this.processError) {
            try {
                const result = await this.actor.getPost(arg0);
                return from_candid_Post_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPost(arg0);
            return from_candid_Post_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPostReactions(arg0: bigint): Promise<ReactionCount> {
        if (this.processError) {
            try {
                const result = await this.actor.getPostReactions(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPostReactions(arg0);
            return result;
        }
    }
    async getPreferredLanguage(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getPreferredLanguage();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPreferredLanguage();
            return result;
        }
    }
    async getPublicProfiles(): Promise<Array<PublicProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublicProfiles();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublicProfiles();
            return result;
        }
    }
    async getUnreadNotificationCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getUnreadNotificationCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUnreadNotificationCount();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async isAdmin(arg0: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAdmin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAdmin(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isFollowing(arg0: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isFollowing(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isFollowing(arg0);
            return result;
        }
    }
    async likePost(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.likePost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.likePost(arg0);
            return result;
        }
    }
    async markNotificationRead(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markNotificationRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markNotificationRead(arg0);
            return result;
        }
    }
    async promoteUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.promoteUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.promoteUser(arg0);
            return result;
        }
    }
    async publishDraft(arg0: bigint): Promise<UpdatePostResult> {
        if (this.processError) {
            try {
                const result = await this.actor.publishDraft(arg0);
                return from_candid_UpdatePostResult_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.publishDraft(arg0);
            return from_candid_UpdatePostResult_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async removeAdmin(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeAdmin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeAdmin(arg0);
            return result;
        }
    }
    async removeAuthor(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeAuthor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeAuthor(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async saveDraft(arg0: string, arg1: string, arg2: string, arg3: Array<Image>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.saveDraft(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveDraft(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async setOwner(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setOwner(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setOwner(arg0);
            return result;
        }
    }
    async setPreferredLanguage(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setPreferredLanguage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setPreferredLanguage(arg0);
            return result;
        }
    }
    async unfollowUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unfollowUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unfollowUser(arg0);
            return result;
        }
    }
    async updateDraft(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: Array<Image>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDraft(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDraft(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async updatePost(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: PostStatus, arg5: Array<Image>): Promise<UpdatePostResult> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePost(arg0, arg1, arg2, arg3, to_candid_PostStatus_n27(this._uploadFile, this._downloadFile, arg4), arg5);
                return from_candid_UpdatePostResult_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePost(arg0, arg1, arg2, arg3, to_candid_PostStatus_n27(this._uploadFile, this._downloadFile, arg4), arg5);
            return from_candid_UpdatePostResult_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUserProfile(arg0);
            return result;
        }
    }
}
function from_candid_CreatePostResult_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CreatePostResult): CreatePostResult {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_DeleteCommentResult_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DeleteCommentResult): DeleteCommentResult {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_EditCommentResult_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EditCommentResult): EditCommentResult {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_GetCommentsResult_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GetCommentsResult): GetCommentsResult {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_PostStatus_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PostStatus): PostStatus {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_Post_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Post): Post {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_UpdatePostResult_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UpdatePostResult): UpdatePostResult {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _PostStatus;
    title: string;
    content: string;
    ownerId: Principal;
    createdAt: _Time;
    likedBy: Array<Principal>;
    author: string;
    dislikedBy: Array<Principal>;
    images: Array<_Image>;
}): {
    id: bigint;
    status: PostStatus;
    title: string;
    content: string;
    ownerId: Principal;
    createdAt: Time;
    likedBy: Array<Principal>;
    author: string;
    dislikedBy: Array<Principal>;
    images: Array<Image>;
} {
    return {
        id: value.id,
        status: from_candid_PostStatus_n18(_uploadFile, _downloadFile, value.status),
        title: value.title,
        content: value.content,
        ownerId: value.ownerId,
        createdAt: value.createdAt,
        likedBy: value.likedBy,
        author: value.author,
        dislikedBy: value.dislikedBy,
        images: value.images
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: bigint;
} | {
    imageTooLarge: null;
}): {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "imageTooLarge";
    imageTooLarge: null;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "imageTooLarge" in value ? {
        __kind__: "imageTooLarge",
        imageTooLarge: value.imageTooLarge
    } : value;
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    notFound: null;
} | {
    notOwner: null;
}): DeleteCommentResult {
    return "ok" in value ? DeleteCommentResult.ok : "notFound" in value ? DeleteCommentResult.notFound : "notOwner" in value ? DeleteCommentResult.notOwner : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    published: null;
} | {
    hidden: null;
} | {
    draft: null;
}): PostStatus {
    return "published" in value ? PostStatus.published : "hidden" in value ? PostStatus.hidden : "draft" in value ? PostStatus.draft : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_Comment>;
} | {
    postNotFound: null;
}): {
    __kind__: "ok";
    ok: Array<Comment>;
} | {
    __kind__: "postNotFound";
    postNotFound: null;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "postNotFound" in value ? {
        __kind__: "postNotFound",
        postNotFound: value.postNotFound
    } : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    postNotFound: null;
} | {
    imageTooLarge: null;
}): UpdatePostResult {
    return "ok" in value ? UpdatePostResult.ok : "postNotFound" in value ? UpdatePostResult.postNotFound : "imageTooLarge" in value ? UpdatePostResult.imageTooLarge : value;
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Post>): Array<Post> {
    return value.map((x)=>from_candid_Post_n16(_uploadFile, _downloadFile, x));
}
function to_candid_PostStatus_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PostStatus): _PostStatus {
    return to_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PostStatus): {
    published: null;
} | {
    hidden: null;
} | {
    draft: null;
} {
    return value == PostStatus.published ? {
        published: null
    } : value == PostStatus.hidden ? {
        hidden: null
    } : value == PostStatus.draft ? {
        draft: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
